on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'Agent Production' || 'Agent Staging' }}
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.DEPLOYER_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Configure docker credentials
      run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_URL }}

    - name: Set tag
      run: echo "TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: Set docker driver
      run: docker buildx create --use --driver=docker-container

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          TAG=${{ env.TAG }}
          SUBSYSTEM=agent
        push: true
        tags: |
          ${{ vars.ECR_URL }}/${{ vars.ECR_REPO }}:${{ env.TAG }}
          ${{ vars.ECR_URL }}/${{ vars.ECR_REPO }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max